name: check nuget version of MamisSolidarias.Utils

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - MamisSolidarias.Utils/**
      - MamisSolidarias.Utils.sln


  workflow_dispatch:

jobs:
  check-nuget-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ldellisola/verify-nuget-package-version@v1.4.0
        with:
            PROJECT_FILE_PATH: 'MamisSolidarias.Utils/MamisSolidarias.Utils.csproj'
