# This is a basic workflow to help you get started with Actions

name: check-nuget-version

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]
    paths:
      - MamisSolidarias.Utils/**
      - MamisSolidarias.Utils.sln


  workflow_dispatch:

jobs:
  check-nuget-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ldellisola/verify-nuget-package-version@v1.2.0
        with:
            PROJECT_FILE_PATH: 'MamisSolidarias.Utils/MamisSolidarias.Utils.csproj'
